---
name: Request missing device configuration
about: Choose this if you want to request a configuration file for a device
title: ''
labels: 'config âš™'
assignees: 

---

<!--
  ðŸš¨ðŸš¨ðŸš¨ STOP! STOP! STOP! ðŸš¨ðŸš¨ðŸš¨
  
  Please fill in the whole issue template. We won't be able to act on it if you don't
-->


**Which device is missing?**

Enter Manufacturer and Device name here

**What are the IDs?**
Manufacturer ID: 0x1234
Product type: 0x4321
Product ID: 0x0101

**Did you check if we really don't have it?**

- [ ] It is not in the [configuration DB](https://devices.zwave-js.io/)
- [ ] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)
- [ ] It is not in the [TODO list](https://github.com/zwave-js/node-zwave-js/issues/1600)

**Do you have a link to the PDF manual?**

If so, it helps in creating the config file.
