name: 'Z-Wave Bot: Auto-Merge'

on:
  issue_comment:
    types: [created] # edited, deleted

jobs:
  # #########################################################################
  # Adds the "automerge" label when an authorized person comments
  # @zwave-js-bot automerge
  add-automerge-label:
    if: |
      contains(github.event.issue.html_url, '/pull/') &&
      contains(github.event.comment.body, '@zwave-js-bot automerge') &&
      (github.event.comment.user.login == 'AlCalzone' || github.event.comment.user.login == 'renovate[bot]')

    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        node-version: [14.x] # This should be LTS

    steps:
    - uses: actions/github-script@v4
      with:
        github-token: ${{secrets.BOT_TOKEN}}
        script: |
          const options = {
            owner: context.repo.owner,
            repo: context.repo.repo,
          };

          await github.issues.addLabels({
            ...options,
            issue_number: context.payload.issue.number,
            labels: ["automerge"]
          });
