name: Generate documentation

# Run this workflow on all pushes to master and pull requests
on:
  push:
    branches:
      - master
  pull_request: {}
  merge_group:
    types: [checks_requested]

# Cancel previous PR/branch runs when a new commit is pushed
concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  # This job checks if the docs can be generated and produce changes
  # If they do, a PR will be created with the changes
  check-and-update:
    # Don't run in forks
    if: github.repository == 'zwave-js/node-zwave-js'

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18] # This should be LTS

    outputs:
      CHANGES: ${{ steps.changes.outputs.CHANGES }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install --immutable

    - name: Compile TypeScript code
      run: yarn run build

    - name: Generate documentation
      run: yarn run docs:generate

    - name: Generate API report
      run: yarn run accept-api

    # Trigger this step only when pushing to master
    - name: Create or update PR
      if: |
        github.event_name == 'push' && 
        github.ref == 'refs/heads/master'
      uses: ./.github/actions/generateTypedDocs
      with:
        githubToken: ${{ secrets.BOT_TOKEN }}
      env:
        CI: true
