name: Publish PR Test Build

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  publish:
    # if: contains(github.event.comment.html_url, '/pull/') # && contains(github.event.comment.body, 'commenttest')
    runs-on: [ubuntu-latest]
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: get pullrequest url
        run: |
          echo ${{ github.event.issue.pull_request.url }}
      - name: get upstream branch
        id: upstreambranch
        run: |
          echo "::set-output name=branchname::$(curl -v -H "Accept: application/vnd.github.sailor-v-preview+json" -u ${{ secrets.PAT }} ${{ github.event.issue.pull_request.url }} | jq '.head.ref' | sed 's/\"//g')"
      - name: echo upstream branch
        run: |
          echo ${{ steps.upstreambranch.outputs.branchname }}
      - name: Checkout upstream repo
        uses: actions/checkout@v2
        with:
           ref: ${{ steps.upstreambranch.outputs.branchname }}
