name: Trigger Bot

on:
  issue_comment:
    types: [created, edited] # deleted

jobs:
  # Publish a PR build when an authorized person comments "@zwave-js-bot pack this"
  publish-pr:
    if: |
      contains(github.event.issue.html_url, '/pull/') &&
      contains(github.event.comment.body, '@zwave-js-bot pack this') &&
      (github.event.comment.user.login == 'AlCalzone')

    runs-on: [ubuntu-latest]
    steps:

    - uses: actions/github-script@v3
      with:
        github-token: ${{secrets.BOT_TOKEN}}
        script: |
          const options = {
            owner: context.repo.owner,
            repo: context.repo.repo,
          };
          const { data: pull } = await github.pulls.get({
            ...options,
            pull_number: context.payload.issue.number,
          });

          if (!pull.mergeable || !pull.merge_commit_sha) {
            await github.issues.createComment({
              ...options,
              issue_number: context.payload.issue.number,
              body: `ðŸ˜¥ Seems like this PR cannot be merged. Please fix the merge conflicts and try again.`,
            });
            process.exit(1);
          }

          await github.issues.createComment({
            ...options,
            issue_number: context.issue.number,
            body: `ðŸ‘‹ Hey @${context.payload.comment.user.login}!
                   I've started to deploy this PR as a development build.
                   You can monitor the progress [here](${context.payload.repository.html_url}/actions/runs/${context.runId}).`
          })

    - name: Checkout merged code
      uses: actions/checkout@v2
      with:
        token: ${{secrets.BOT_TOKEN}}
        ref: 'refs/pull/${{ github.event.issue.number }}/merge'

    - name: Switch to a branch
      run: git switch -c temp

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Let the bot do its thing
      uses: ./.github/actions/zwave-js-bot
      with:
        githubToken: ${{ secrets.BOT_TOKEN }}
        npmToken: ${{ secrets.NPM_TOKEN }}
        task: publish-pr
        pr: ${{ github.event.issue.number }}
